spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwtdemo
jwt:
  access:
    jwtProperty:
      jks:
        password: "changeit"
        path: "access-keystore.jks"
      key:
        alias: "keyAliasAccess"
        password: "changeit"
      expiration: 600000
  refresh:
    jwtProperty:
      jks:
        password: "changeit"
        path: "refresh-keystore.jks"
      key:
        alias: "keyAliasRefresh"
        password: "changeit"
      expiration: 3600000