spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwtdemo
jwt:
  jwtSecret: changeThisSecret
  refreshTokenSecret: changeThisRefreshTokenSecret
  expiration: 600000
  refreshTokenExpiration: 3600000
