spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwtdemo
jwt:
  accessTokenSecret: changeThisSecret
  accessTokenExpiration: 600000
  refreshTokenSecret: changeThisRefreshTokenSecret
  refreshTokenExpiration: 3600000
