spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwtdemo
jwt:
  key:
    access:
      alias: "keyAliasAccess"
      keystoreJks: "access-keystore.jks"
      jksPassword: "changeit"
      keyPassword: "changeit"
      expiration: 600000
    refresh:
      alias: "keyAliasRefresh"
      keystoreJks: "refresh-keystore.jks"
      jksPassword: "changeit"
      keyPassword: "changeit"
      expiration: 3600000